### ISSUE TITLE
Dagger.android 使用优化

### ISSUE THREAD

**Issue by FloraFang12345** [AnyLifeZLB/Android-Architecture#4]
在XXModuleAllActivityModule 中我们每次新建一个Activity，只需要统一在这里新建2行代码声明对应的Activity即可 

我想咨询的是能否更加的精简，不需要新建2行代码声明，
直接在对应的Activity 中添加一个注解就可以，都要这样配置还是有点重复无聊的感觉

**Comment by FaceAISDK** [comment]
我也在想能否精简，Maybe later
