### ISSUE TITLE
在loggin中做requestIdsMap.remove是不对的

### ISSUE THREAD

**Issue by XuanJiAndroid** [AnyLifeZLB/Android-Architecture#5]
如题，在loggin中做requestIdsMap.remove是不对的，实测在混淆后会导致requestIdsMap.put死锁，正确的做法是在[此处](https://github.com/AnyLifeZLB/MVP-Dagger2-Rxjava2/blob/7f7db30de4938a315c3b8188cc263401a52d691e/baselib/src/main/java/com/zlb/http/HttpRetrofit.java#L130)做remove处理，且需要将Map的声明，改为 
` private static final `比较妥当。

**Comment by FaceAISDK** [comment]
关闭了，没有注意看
